const todos = [
  {
    id: 1,
    title: "delectus aut autem",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 2,
    title: "quis ut nam facilis et officia qui",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 3,
    title: "fugiat veniam minus",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 4,
    title: "et porro tempora",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 5,
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 6,
    title: "qui ullam ratione quibusdam voluptatem quia omnis",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 7,
    title: "illo expedita consequatur quia in",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 8,
    title: "quo adipisci enim quam ut ab",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 9,
    title: "molestiae perspiciatis ipsa",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 10,
    title: "illo est ratione doloremque quia maiores aut",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 11,
    title: "vero rerum temporibus dolor",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 12,
    title: "ipsa repellendus fugit nisi",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 13,
    title: "et doloremque nulla",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 14,
    title: "repellendus sunt dolores architecto voluptatum",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 15,
    title: "ab voluptatum amet voluptas",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 16,
    title: "accusamus eos facilis sint et aut voluptatem",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 17,
    title: "quo laboriosam deleniti aut qui",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 18,
    title: "dolorum est consequatur ea mollitia in culpa",
    desc: "",
    deadline: "2022-06-23",
    completed: false,
  },
  {
    id: 19,
    title: "molestiae ipsa aut voluptatibus pariatur dolor nihil",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
  {
    id: 20,
    title: "ullam nobis libero sapiente ad optio sint",
    desc: "",
    deadline: "2022-06-23",
    completed: true,
  },
];

module.exports = { todos };
