module.exports.todos = [
  {
    id: 1,
    title: "Do something nice for someone I care about",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-01",
    completed: true,
  },
  {
    id: 2,
    title: "Memorize the fifty states and their capitals",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-03",
    completed: false,
  },
  {
    id: 3,
    title: "Watch a classic movie",
    desc: "Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet",
    deadline: "2022-07-05",
    completed: false,
  },
  {
    id: 4,
    title:
      "Contribute code or a monetary donation to an open-source software project",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-07",
    completed: false,
  },
  {
    id: 5,
    title: "Solve a Rubik's cube",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-08",
    completed: false,
  },
  {
    id: 6,
    title: "Bake pastries for me and neighbor",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-11",
    completed: false,
  },
  {
    id: 7,
    title: "Go see a Broadway production",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-13",
    completed: false,
  },
  {
    id: 8,
    title: "Write a thank you letter to an influential person in my life",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-15",
    completed: true,
  },
  {
    id: 9,
    title: "Invite some friends over for a game night",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-17",
    completed: false,
  },
  {
    id: 10,
    title: "Have a football scrimmage with some friends",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-18",
    completed: false,
  },
  {
    id: 11,
    title: "Text a friend I haven't talked to in a long time",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-22",
    completed: false,
  },
  {
    id: 12,
    title: "Organize pantry",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-07-25",
    completed: true,
  },
  {
    id: 13,
    title: "Buy a new house decoration",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-09-01",
    completed: false,
  },
  {
    id: 14,
    title: "Plan a vacation I've always wanted to take",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-10-05",
    completed: false,
  },
  {
    id: 15,
    title: "Clean out car",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-11-11",
    completed: false,
  },
  {
    id: 16,
    title: "Draw and color a Mandala",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2022-12-21",
    completed: true,
  },
  {
    id: 17,
    title: "Create a cookbook with favorite recipes",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-01-22",
    completed: false,
  },
  {
    id: 18,
    title: "Bake a pie with some friends",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-01-07",
    completed: false,
  },
  {
    id: 19,
    title: "Create a compost pile",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-02-26",
    completed: true,
  },
  {
    id: 20,
    title: "Take a hike at a local park",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-03-06",
    completed: true,
  },
  {
    id: 21,
    title: "Take a class at local community center that interests you",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-03-20",
    completed: false,
  },
  {
    id: 22,
    title: "Research a topic interested in",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-04-10",
    completed: false,
  },
  {
    id: 23,
    title: "Plan a trip to another country",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-05-02",
    completed: true,
  },
  {
    id: 24,
    title: "Improve touch typing",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2023-05-08",
    completed: false,
  },
  {
    id: 25,
    title: "Learn Express.js",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2024-08-16",
    completed: false,
  },
  {
    id: 26,
    title: "Learn calligraphy",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2024-08-17",
    completed: false,
  },
  {
    id: 27,
    title: "Have a photo session with some friends",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2024-09-14",
    completed: false,
  },
  {
    id: 28,
    title: "Go to the gym",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2024-10-19",
    completed: false,
  },
  {
    id: 29,
    title: "Make own LEGO creation",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2024-11-09",
    completed: false,
  },
  {
    id: 30,
    title: "Take cat on a walk",
    desc: "Lorem ipsum dolor sit amet",
    deadline: "2024-12-11",
    completed: false,
  },
];
